Implement typescript driver
bblfsh/typescript-driver pull request #1
Opened 2017-02-27 14:38 UTC by erizocosmico

/cc @Serabe @smola @mcuadros 

P.D.: Can we pretty please give permissions in this org so we can assign reviewers instead of cc'ing?

2017-02-28 11:42 UTC, erizocosmico commented
Updated with JSDoc comment parsing and non-JSDoc comment extraction.

2017-03-01 10:05 UTC, smola approved these changes

2017-03-06 14:37 UTC, Serabe requested changes

2017-03-06 14:37 UTC, Serabe commented on native/src/index.js
> +rl.on('line', l => console.log(processRequest(l)));
I tend to prefer streams for this kind of transforming. No no-go. Just the solution for javascript will be different xD.

2017-03-06 14:37 UTC, Serabe commented on Dockerfile.build
> +FROM node:7-alpine
We need to talk about which version of node we should use. I was planning on using LTS, but open to other policies.

2017-03-06 14:37 UTC, Serabe commented on .travis.yml
> +language: go
I thought @mcuadros said we should not be using sdk yet.

2017-03-06 14:37 UTC, Serabe commented on README.md
> +`docker run -it bblfsh/java-driver:dev-<commit[:6]>`
s/java/typescript/

This is solved in sdk now.

2017-03-06 14:41 UTC, erizocosmico commented on native/src/index.js
> +rl.on('line', l => console.log(processRequest(l)));
:trollface: now it's the same in javascript's, so I get i don't have to changes this

2017-03-06 14:42 UTC, erizocosmico commented on Dockerfile.build
> +FROM node:7-alpine
we can perfectly use the LTS, was the first that I found, tbh. Anyway, Dockerfiles are bound to change once the SDK is ready to use, so they will get changed and then we'll decide what version to use. But yeah, LTS makes sense

2017-03-06 14:42 UTC, erizocosmico commented on .travis.yml
> +language: go
yep, but since it's already there /shrug

2017-03-06 16:01 UTC, Serabe commented on native/src/index.js
> +rl.on('line', l => console.log(processRequest(l)));
Yep, really all crappy comment of mine.

Why do all nasty advertisements launch a confirm dialog before leaving but Github does not?

2017-03-06 16:01 UTC, Serabe approved these changes

2017-03-06 17:08 UTC, merged

2017-03-06 19:43 UTC, erizocosmico commented on native/src/index.js
> +rl.on('line', l => console.log(processRequest(l)));
i guess we'll never know